# ##
# WARNING: absolute use space instead of tab to indent file.
# ##

# reference site
url: "https://www.xtrmaddons.com/"

# generic title.
title: XtrmAddons Assets

# generic description.
description: XtrmAddons assets and documentation examples.

# see : https://github.com/pages-themes/slate
theme: jekyll-theme-slate

# "true" or "false" to show page header.
show_page_header: true

# "true" or "false" to indicate whether to provide a download URL
show_downloads: true

# show main navigation bar.
show_navbar: true

# navbar brand type: [icon|img]
navbar_brand_type: "icon"

# navbar brand icon
navbar_brand_icon: "glyphicon-home"

# navbar brand image
navbar_brand_img: "./assets/images/logo.png"

# navbar brand title
navbar_brand_title: "XtrmAddons"

# Your Google Analytics tracking ID
# google_analytics: [Your Google Analytics tracking ID]