# ##
# WARNING: absolute use space instead of tab to indent file.
# ##

# generic title.
title: XtrmAddons Assets

# generic description.
description: XtrmAddons assets and documentation examples.

# see : https://github.com/pages-themes/slate
# theme: jekyll-theme-slate

# "true" or "false" to indicate whether to provide a download URL
show_downloads: true

# show main navigation bar.
show_navbar: true

# Your Google Analytics tracking ID
# google_analytics: [Your Google Analytics tracking ID]