# ##
# WARNING: absolute use space instead of tab to indent file.
# ##

# reference site
url: "https://www.xtrmaddons.com/"

# company or user name
author: "XtrmAddons"

# generic title.
title: XtrmAddons Assets

# generic description.
description: XtrmAddons assets and documentation examples.

# generic assets link root.
assets: ""

# pages collection
# see : https://jekyllrb.com/docs/collections/
collections_dir: "docs"

# "true" or "false" to show page header.
show_page_header: true

# "true" or "false" to indicate whether to provide a download URL
show_downloads: true

# show main navigation bar.
show_navbar: true

# navbar brand type: [icon|img]
navbar_brand_type: "img"

# navbar brand icon
navbar_brand_icon: "glyphicon-home"

# navbar brand image
navbar_brand_img: "/assets/images/logo.png"

# navbar brand title
navbar_brand_title: "XtrmAddons"

# navbar brand
brand:
  copyright:
    date_start: "2007"
    date_end: "2019"

# Your Google Analytics tracking ID
google_analytics: "UA-107731670-1"