# ##
# WARNING: absolute use space instead of tab to indent file.
# ##

# see : https://github.com/pages-themes/slate
theme: jekyll-theme-slate

# reference site
url: "https://www.xtrmaddons.com/"

# company or user name
author: "XtrmAddons"

# generic title.
title: XtrmAddons Assets

# generic description.
description: XtrmAddons assets and documentation examples.

# Generic assets links.
assets:
  css: "https://github.assets.xtrmaddons.com/assets/css/"
  img: "https://github.assets.xtrmaddons.com/assets/images/"
  js: "https://github.assets.xtrmaddons.com/assets/js/"

# navbar
navbar:
  brand:
    icon: "glyphicon-home"
    img: "logo-name.svg"
    title: ""
    type: "img"

# pages collection
# see : https://jekyllrb.com/docs/collections/
collections_dir: "docs"

# navbar brand
brand:
  copyright:
    date_start: "2007"
    date_end: "2019"

# Your Google Analytics tracking ID
google_analytics: "UA-107731670-1"