title: XtrmAddons Assets 
description: XtrmAddons assets and documentation examples.

# see : https://github.com/pages-themes/slate
theme: jekyll-theme-slate

# "true" or "false" to indicate whether to provide a download URL
show_downloads: "false"

# show main navigation bar.
show_show_navbar: "false"

# Your Google Analytics tracking ID
# google_analytics: [Your Google Analytics tracking ID]